### ISSUE TITLE
How can I deploy this project into heroku

### ISSUE THREAD

**Issue by kentdev92** [fifijo/react-seo-boilerplate#1]
The first I'm want to say thank you so much for create this boilerplate!
It's very clean code, structure.
And i love this boilerplate.
But could you please add more how can deploy this to heroku.
Thank you so much and have a nice day

**Comment by fifijo** [comment]
@kentdev92 Hi, just have a look at this tutorial https://www.freecodecamp.org/news/deploy-a-react-node-app-to/
